{
  "noiseKey": {
    "private": {
      "type": "Buffer",
      "data": "qBkoFV9p5daWvvw6zCTQ+qn3+wKgeLLZF4Y+nQeZWEs="
    },
    "public": {
      "type": "Buffer",
      "data": "/MIeFDJ4ztPq8Mf1M7AvfVsubvHhaNl4S4l+QRgcFgg="
    }
  },
  "pairingEphemeralKeyPair": {
    "private": {
      "type": "Buffer",
      "data": "iF0ifRyfV1ve4ePFhkDasQg1NEq/cNU2YSMIG4bf13U="
    },
    "public": {
      "type": "Buffer",
      "data": "wqMmYdVfyPvRgwYmazK3WuviC0R8391dhwSxb825uXU="
    }
  },
  "signedIdentityKey": {
    "private": {
      "type": "Buffer",
      "data": "CA5+0r2PGctUmXCYnSfJcmrfgCSl7Ny68txuvAWUc24="
    },
    "public": {
      "type": "Buffer",
      "data": "H/l7eMhC3vjSPFELpQuVvB8WGbtbQZ8dP/OjEIpGYlA="
    }
  },
  "signedPreKey": {
    "keyPair": {
      "private": {
        "type": "Buffer",
        "data": "CF86SK8F4IGkzakCxrOYOIAhsED9yAwNCHlgDEuXgkQ="
      },
      "public": {
        "type": "Buffer",
        "data": "9zgSYoeSmX768DY1TTJgJycWYWf8ERzHZUlAIDG82Rs="
      }
    },
    "signature": {
      "type": "Buffer",
      "data": "S1An3OzsQDZj84dV4C4o52ptiKI9gHWfE/6UsCE8QHtReTy/Mkd13ZmQ0CY9AAAvE7ZRRjPRNCCSvRNeDtYkDw=="
    },
    "keyId": 1
  },
  "registrationId": 191,
  "advSecretKey": "jrWuy4WWCAMuUwdfEEc81KD2BPwx2Fkfgr7ow/OkRtQ=",
  "processedHistoryMessages": [],
  "nextPreKeyId": 31,
  "firstUnuploadedPreKeyId": 31,
  "accountSyncCounter": 0,
  "accountSettings": {
    "unarchiveChats": false
  },
  "registered": true,
  "pairingCode": "17PKWVSM",
  "me": {
    "id": "923346864922:8@s.whatsapp.net",
    "lid": "248516035268836:8@lid"
  },
  "account": {
    "details": "CMie9YkDEK/3rMoGGAEgACgA",
    "accountSignatureKey": "s+wRvPWPW/P2N99biywgrO1M7Zo8QC+y6QtHrLU+LDo=",
    "accountSignature": "ow1mmiyVEmOXFEXfvrId5Xuy/tBNWG7zi4akR+T84CxSgZ9VfTvBJRoslUnFM05+EHoym/JWAuCS9Zo/Wh9cDw==",
    "deviceSignature": "n7TMvceyH3UFyIT/H2W4FgCfD6fFxX3zytG3MfiRbqbSl6OtXRQOHO88NwXQJsdXBSOuJvIb391fBjMNRtHSAw=="
  },
  "signalIdentities": [
    {
      "identifier": {
        "name": "923346864922:8@s.whatsapp.net",
        "deviceId": 0
      },
      "identifierKey": {
        "type": "Buffer",
        "data": "BbPsEbz1j1vz9jffW4ssIKztTO2aPEAvsukLR6y1Piw6"
      }
    }
  ],
  "platform": "android",
  "routingInfo": {
    "type": "Buffer",
    "data": "CAIIEggN"
  },
  "lastAccountSyncTimestamp": 1766538163,
  "lastPropHash": "2V77qU"
}
